# Generated by Django 4.1.7 on 2023-03-26 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FormatRule',
            fields=[
                ('format_rule_id', models.IntegerField(primary_key=True, serialize=False)),
                ('position_in_name', models.IntegerField()),
                ('digits_number_start', models.IntegerField()),
                ('digits_number_end', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('item_number', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('unit', models.CharField(max_length=20)),
                ('manual_id', models.IntegerField()),
                ('state', models.CharField(max_length=50)),
                ('item_type', models.CharField(max_length=50)),
                ('assembly_time', models.FloatField()),
                ('machine_time', models.FloatField()),
                ('needs_time', models.BooleanField()),
                ('needs_instructions', models.BooleanField()),
                ('needs_sn', models.BooleanField()),
                ('needs_lot_no', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='ItemGroup',
            fields=[
                ('group_id', models.CharField(max_length=1, primary_key=True, serialize=False)),
                ('format_rule_id', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Manual',
            fields=[
                ('manual_id', models.IntegerField(primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('tools', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='StorageArea',
            fields=[
                ('storage_area_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='StorageLocation',
            fields=[
                ('storage_location_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('storage_area_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bomwizard.storagearea')),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('supplier_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('mail', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('website', models.CharField(max_length=100)),
                ('customer_id', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('tool_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('power', models.BooleanField()),
                ('fixed', models.BooleanField()),
                ('storage_location_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bomwizard.storagelocation')),
            ],
        ),
        migrations.CreateModel(
            name='ItemSupplier',
            fields=[
                ('item_supplier_id', models.IntegerField(primary_key=True, serialize=False)),
                ('supplier_item_number', models.CharField(max_length=50)),
                ('supplier_description', models.TextField()),
                ('price', models.FloatField()),
                ('item_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bomwizard.item')),
                ('supplier_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bomwizard.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='ItemSubGroup',
            fields=[
                ('category_id', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('format_rule_id', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bomwizard.itemgroup')),
            ],
        ),
        migrations.CreateModel(
            name='ItemBOM',
            fields=[
                ('item_bom_id', models.IntegerField(primary_key=True, serialize=False)),
                ('used_item_number', models.CharField(max_length=20)),
                ('quantity', models.FloatField()),
                ('item_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bomwizard.item')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='group_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bomwizard.itemgroup'),
        ),
        migrations.AddField(
            model_name='item',
            name='project_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bomwizard.project'),
        ),
        migrations.AddField(
            model_name='item',
            name='storage_location_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bomwizard.storagelocation'),
        ),
        migrations.AddField(
            model_name='item',
            name='sub_group_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bomwizard.itemsubgroup'),
        ),
    ]
